version: '2'

services:
  couchbase:
    build: ./couchbase
    image: todo/couchbase
    ports:
      - "8091-8093:8091-8093"
      - "11210:11210"

  todo-app:
    build: ./todo-app
    image: todo/app
    depends_on:
      - "couchbase"
    restart: always